AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "helloworld\nSample SAM Template for helloworld\n"
Parameters:
  EnvName:
    Type: String
    Default: dev
    Description: Selecciona el nombre ambiente que quieres desplegar
  DBEnvName:
    Type: String
    Default: dev
    Description: Valor de sufijo para tablas de base de datos
  ParametersKMSARN:
    Description: ARN de la llave que descifra los secretos
    Type: String
Globals:
  Function:
    Timeout: 3
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref 'EnvName'
      Name: ejemplo-apigateway
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub HelloWorld-StateMachine
      StateMachineType: STANDARD
      DefinitionString: empty
      RoleArn: arn:aws:iam::111122223333:role/service-role/StatesExecutionRole-us-east-1;
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub SampleQueue
  EventRuleRegion1:
    Type: AWS::Events::Rule
    Properties:
      Description: Routes to us-east-1 event bus
      EventBusName: !Sub 'MyBusName'
      State: ENABLED
      EventPattern:
        source:
          - MyTestApp
        detail:
          - MyTestAppDetail
      Targets:
        - Arn: arn:aws:events:us-east-1:123456789012:event-bus/CrossRegionDestinationBus
          Id: ' CrossRegionDestinationBus'
          RoleArn: !GetAtt 'EventBridgeIAMrole.Arn'
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'DOC-EXAMPLE-BUCKET'
  HelloWorldFunction0:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'EnvName'
      Name: ejemplo-apigateway
  ApiGatewayApi3:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref 'EnvName'
      Name: ejemplo-apigateway
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'ejemplo-lambda-${EnvName}'
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref 'ApiGatewayApi'
            Path: /hello
            Method: get
      Environment:
        Variables:
          TABLA_EJEMPLO: !Sub 'ejemplo-tabla-ejemplo-${DBEnvName}'
      Policies:
        - AmazonS3ReadOnlyAccess
        - SSMParameterReadPolicy:
            ParameterName: !Sub 'sia-utileria-parametro-${EnvName}'
        - DynamoDBCrudPolicy:
            TableName: !Sub 'sia-catalogo-ejemplo-${DBEnvName}'
        - Statement:
            - Sid: KMSDescifrar
              Effect: Allow
              Action:
                - kms:Decrypt
              Resource: !Ref 'ParametersKMSARN'
        - Statement:
            - Sid: KMSCifrar
              Effect: Allow
              Action:
                - kms:Encrypt
              Resource: !Ref 'ParametersKMSARN'
